### ISSUE TITLE
[Feat] Add Telegram Bot Push

### ISSUE THREAD

**Issue by gitiray** [ThreeCatsLoveFish/MedalHelper#10]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Support more push notifications, for example telegram

**Describe alternatives you've considered**
no

**Additional context**
https://core.telegram.org/bots/api#sendmessage
https://github.com/whyour/qinglong/blob/d43cee53c9cd4af752d50fd2c459de392c41eb38/sample/notify.js#L52

**Comment by ThreeCatsLoveFish** [comment]
Good idea, you mean the telegram bots right?

**Comment by gitiray** [comment]
对，已经用上了，谢谢！（看到英文模板所以用的英文哈哈
