### ISSUE TITLE
[BUG] Multi account execute error

### ISSUE THREAD

**Issue by gitiray** [ThreeCatsLoveFish/MedalHelper#16]
**Describe the bug**

AB两个帐号，按要求写好配置文件，已检测无格式问题，运行后查看日志，会：
1. 提示B帐号未登录
2. A帐号执行完签到任务后，不会有其它任务的执行日志（检查b站那边，当天牌子经验也为0，说明确实没有执行）
3. B帐号正确执行并显示日志

**Screenshots**
```
2022/05/31 00:33:22 [INFO] 外部调用,开启任务
2022/05/31 00:33:23 A帐号 [INFO] 登录成功
2022/05/31 00:33:23 A帐号 [INFO] 今日已签到过,无法重复签到
2022/05/31 00:33:23 A帐号 [INFO] 当前用户UL等级:  还差 经验升级
2022/05/31 00:33:24 [ERROR]用户未登录, accessKey: xxxxxxxxxxxxxxxx（B帐号的key）
2022/05/31 00:33:24 B帐号 [INFO] 登录成功
2022/05/31 00:33:24 B帐号 [INFO] 今日已签到过,无法重复签到
2022/05/31 00:33:24 B帐号 [INFO] 当前用户UL等级:还差 经验升级
2022/05/31 00:33:25 B帐号 [INFO] xxxx 房间心跳包已发送(1/31)
……
```

**Docker (please complete the following information):**
 - Docker Version: https://github.com/ThreeCatsLoveFish/MedalHelper/commit/d055acce003c0755688506eddb456c7af9c3a8aa

**Additional context**
两个key均为有效状态，尝试单独注释帐号A或帐号B，均能正常执行

**Comment by ThreeCatsLoveFish** [comment]
Interesting 我明天看下这个是啥问题


------------------ 原始邮件 ------------------
From: GitiRay ***@***.***&gt;
发送时间: 05/31/2022, 00:50
To: ThreeCatsLoveFish/MedalHelper ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
Subject: Re: [ThreeCatsLoveFish/MedalHelper] [BUG] 多账号执行故障 (Issue #16)





 
Describe the bug
 
AB两个帐号，按要求写好配置文件，已检测无格式问题，运行后查看日志，会：
  
提示B帐号未登录 

A帐号执行完签到任务后，不会有其它任务的执行日志 

B帐号正确执行并显示日志 
 
Screenshots
 2022/05/31 00:33:22 [INFO] 外部调用,开启任务 2022/05/31 00:33:23 A帐号 [INFO] 登录成功 2022/05/31 00:33:23 A帐号 [INFO] 今日已签到过,无法重复签到 2022/05/31 00:33:23 A帐号 [INFO] 当前用户UL等级:  还差 经验升级 2022/05/31 00:33:24 [ERROR]用户未登录, accessKey: xxxxxxxxxxxxxxxx（B帐号的key） 2022/05/31 00:33:24 B帐号 [INFO] 登录成功 2022/05/31 00:33:24 B帐号 [INFO] 今日已签到过,无法重复签到 2022/05/31 00:33:24 B帐号 [INFO] 当前用户UL等级:还差 经验升级 2022/05/31 00:33:25 B帐号 [INFO] xxxx 房间心跳包已发送(1/31) ……  
Docker (please complete the following information):
  
Docker Version: d055acc 
 
Additional context
 两个key均为有效状态，尝试单独注释帐号A或帐号B，均能正常执行

**Comment by ThreeCatsLoveFish** [comment]
应该是一个bug，我是指针操作的，但是这个变量原本的作用域不够，传到协程里面可能就撞了，好兄弟如果有空的话能帮我测试一下吗？我手头上只有一个号

**Comment by ThreeCatsLoveFish** [comment]
借了朋友的号测试了一下，应该是修好了

**Comment by gitiray** [comment]
抱歉上午不在线，已拉取新版测试正常！
感谢💗
