### ISSUE TITLE
[Feat] Wear medal before sending danmu

### ISSUE THREAD

**Issue by NyE1125** [ThreeCatsLoveFish/MedalHelper#17]
有的直播间开启了粉丝牌禁言，必须佩戴粉丝牌才能发言。
是否可以在user.yaml中添加一项：switchmedal_uid，让用户自己添加应该切换粉丝牌的直播间？
如果做不到切换粉丝牌，也可以设置为跳过这些直播间的发言打卡，同时判定该直播间亲密度>=1200时就结束。

不知道算不算Bug，也可能是因为我设置任务失败最多重试次数太高的原因：
当某个直播间开启了粉丝牌禁言，无法完成弹幕打卡时，程序会因为该直播间亲密度未>=1300而重复执行打卡程序，日志如下：
【1300及以上】 ....
【1200至1300】 [泛式 老番茄]等 2个
【1100至1200】 []等 0个
【1100以下】 []等 0个
2022/05/31 02:28:13 XXXXX [INFO] 老番茄 房间心跳包已发送(1/31)
2022/05/31 02:28:13 XXXXX [INFO] 泛式 房间心跳包已发送(1/31)
2022/05/31 02:28:25 XXXXX [INFO] 点赞完成
2022/05/31 02:28:43 XXXXX [INFO] 分享完成
2022/05/31 02:29:14 XXXXX [INFO] 泛式 房间心跳包已发送(2/31)
2022/05/31 02:29:14 XXXXX [INFO] 老番茄 房间心跳包已发送(2/31)
2022/05/31 02:30:14 XXXXX [INFO] 老番茄 房间心跳包已发送(3/31)
2022/05/31 02:30:14 XXXXX [INFO] 泛式 房间心跳包已发送(3/31)
2022/05/31 02:31:14 XXXXX [INFO] 泛式 房间心跳包已发送(4/31)
2022/05/31 02:31:14 XXXXX [INFO] 老番茄 房间心跳包已发送(4/31)
2022/05/31 02:32:11 XXXXX [INFO] 老番茄 房间弹幕打卡完成
2022/05/31 02:32:11 XXXXX [INFO] 弹幕打卡未完成,剩余(1/55)
2022/05/31 02:32:14 XXXXX [INFO] 泛式 房间心跳包已发送(5/31)
2022/05/31 02:32:14 XXXXX [INFO] 老番茄 房间心跳包已发送(5/31)
....
之后一直重复

平台：Windows10 
使用Release v1.0 的可执行程序medal_win.exe

**Comment by ThreeCatsLoveFish** [comment]
> 有的直播间开启了粉丝牌禁言，必须佩戴粉丝牌才能发言。 是否可以在user.yaml中添加一项：switchmedal_uid，让用户自己添加应该切换粉丝牌的直播间？ 如果做不到切换粉丝牌，也可以设置为跳过这些直播间的发言打卡，同时判定该直播间亲密度>=1200时就结束。

很巧，我正好想要今天加一下这个功能，但是按照我的经验老番茄直播间就是打不上去，不知道是不是要佩戴粉丝牌，因为我电脑端自己一打就可以。泛式直播间应该是没有问题，可能是个例

> 不知道算不算Bug，也可能是因为我设置任务失败最多重试次数太高的原因： 当某个直播间开启了粉丝牌禁言，无法完成弹幕打卡时，程序会因为该直播间亲密度未>=1300而重复执行打卡程序

默认是重试三次

**Comment by ThreeCatsLoveFish** [comment]
泛式直播间开了需要佩戴粉丝牌，老番茄是另外一类打不上，可能需要手打，解决方案之后要看下

**Comment by ThreeCatsLoveFish** [comment]
已经合入master，预计今天发 v1.1 小版本release，感谢提feature
