### ISSUE TITLE
[Feat] Docker cron improvement

### ISSUE THREAD

**Issue by gitiray** [ThreeCatsLoveFish/MedalHelper#23]
**Is your feature request related to a problem? Please describe.**
有时（网络中断、设备断线、容器停止等）可能出现cron运行被错过、或运行不完整，为了完成当天的任务，需要手动重新运行。
但因为cron 是写在配置文件里面的，需要注释掉文件里cron的时间，再重启容器。等待重新执行完成后，还需要去掉文件里刚才注释的时间，再重启容器，否则会循环多次执行任务。
整个操作比较繁琐。

**Describe the solution you'd like**
改为使用 docker run 命令定义cron
```
docker run -d \
    -e TZ=Asia/Shanghai \
    -v $(pwd)/users.yaml:/config/users.yaml \
    --restart unless-stopped \
    --name medalhelper \
    medalhelper
    3 2 1 * *
```
若最后不添加cron，立即执行。添加cron，则按指定时间执行。

此时，若需要重新执行一次，则只需另开一个容器 `docker run -d --rm -e TZ=Asia/Shanghai -v $(pwd)/users.yaml:/config/users.yaml --restart unless-stopped medalhelper` ，无需改动配置文件，无需触碰定时的容器，且新容器运行完成后也会自动删除

**Comment by ThreeCatsLoveFish** [comment]
我不太清楚docker是如何传参数进入容器的，但是现在你直接跑

```bash
medalhelper start
```

是会立刻进行一次的
不知道这个是否满足你的需求

**Comment by gitiray** [comment]
很好，正好是我想要的状态！
谢谢告知，可以加进文档里喔😄
