### ISSUE TITLE
白名单相关问题

### ISSUE THREAD

**Issue by Malus-Mill** [ThreeCatsLoveFish/MedalHelper#25]
如题
详见python版issues
![image](https://user-images.githubusercontent.com/53999738/178150720-84b2836e-ff36-4af6-8461-e4796c8c7015.png)
之后就会闪退

**Comment by ThreeCatsLoveFish** [comment]
方便把配置文件里面的白名单填的内容发一下吗

**Comment by Malus-Mill** [comment]
USERS:
  - access_key: XXX # 注意冒号后的空格 否则会读取失败 英文冒号
    allowed_uid: 23553760,23240551,14327465,21693691,399,958617,631,22686795 # 白名单UID,填了后将覆盖配置只打卡，点赞，分享这些用户的勋章 用英文逗号分隔 不填则不限制
    banned_uid: 789,100,884239,14085407,23455498,2416317,22435949,23031701 # 黑名单UID,填了后将不会打卡，点赞，分享 用英文逗号分隔 不填则不限制
    push_name:  # 推送服务，留空表示不需要推送
  - access_key:
    allowed_uid:
    banned_uid:
    push_name:
  # 注意对齐
  # 多用户以上格式添加
  # 井号后为注释 井号前后必须有空格
DANMU:
  [
    ".",
  ]
  # 可在此处自定义打卡弹幕
CRON: #3 2 1 * *
# 这里是 cron 表达式, 从左到右参数为秒，分钟，小时，日期，月份
# Second | Minute | Hour | Dom | Month
# 例如每天凌晨01点02分03秒执行一次为 3 2 1 * *
# 如果不填,则不使用内置定时器,填写正确后要保持该进程一直运行
CD:
  async: 0 # 异步执行，默认为1表示异步，0表示同步
  retry: 1 # 任务失败重试时间，单位秒，设置为0不重试
  max_try: 10 # 任务失败最多重试次数，单位次，设置为0不重试
  like: 5 # 点赞间隔时间，单位秒，设置为0不点赞
  share: 10 # 分享间隔时间，单位秒，设置为0不分享
  danmu: 5 # 弹幕间隔时间，单位秒，设置为0不发送弹幕，只支持同步
PUSH:
  - name: "PUSH_DEER_SAMPLE" # 推送名称，对应上面对应用户的推送，请保证名称唯一
    token: "<YOUR-TOKEN-HERE>" # 推送服务TOKEN
    type: "push_deer" # 推送服务类型为 PushDeer
    url: "http://<pushdeer-url-or-ip>/message/push" # 推送服务URL
  - name: "PUSH_PLUS_SAMPLE"
    token: "<YOUR-TOKEN-HERE>"
    type: "push_plus"
    url: "http://www.pushplus.plus/send"
  - name: "TELEGRAM_SAMPLE"
    token: "<YOUR-TELEGRAM-CHATID>"
    type: "telegram"
    url: "https://api.telegram.org/bot<YOUR-BOT-TOKEN-HERE>/sendMessage"
  # 推送服务，每日打卡成功或报错日志推送
  # 目前支持PushDeer, PushPlus, Telegram

**Comment by Malus-Mill** [comment]
?

**Comment by ThreeCatsLoveFish** [comment]
我忘记我的代码逻辑了，但是你又有黑又有白的是什么操作呀



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: PlayerNeo ***@***.***&gt;
发送时间: 2022年7月11日 00:34
收件人: ThreeCatsLoveFish/MedalHelper ***@***.***&gt;
抄送: Zhimin Sun ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [ThreeCatsLoveFish/MedalHelper] 和python版的一样、白名单也是坏的 (Issue #25)





 
USERS:
  
access_key: XXX # 注意冒号后的空格 否则会读取失败 英文冒号
 allowed_uid: 23553760,23240551,14327465,21693691,399,958617,631,22686795 # 白名单UID,填了后将覆盖配置只打卡，点赞，分享这些用户的勋章 用英文逗号分隔 不填则不限制
 banned_uid: 789,100,884239,14085407,23455498,2416317,22435949,23031701 # 黑名单UID,填了后将不会打卡，点赞，分享 用英文逗号分隔 不填则不限制
 push_name:  # 推送服务，留空表示不需要推送 

access_key:
 allowed_uid:
 banned_uid:
 push_name: 
 
注意对齐
 
多用户以上格式添加
 
井号后为注释 井号前后必须有空格
 
DANMU:
 [
 ".",
 ]
 
可在此处自定义打卡弹幕
 
CRON: #3 2 1 * *
 
这里是 cron 表达式, 从左到右参数为秒，分钟，小时，日期，月份
 
Second | Minute | Hour | Dom | Month
 
例如每天凌晨01点02分03秒执行一次为 3 2 1 * *
 
如果不填,则不使用内置定时器,填写正确后要保持该进程一直运行
 
CD:
 async: 0 # 异步执行，默认为1表示异步，0表示同步
 retry: 1 # 任务失败重试时间，单位秒，设置为0不重试
 max_try: 10 # 任务失败最多重试次数，单位次，设置为0不重试
 like: 5 # 点赞间隔时间，单位秒，设置为0不点赞
 share: 10 # 分享间隔时间，单位秒，设置为0不分享
 danmu: 5 # 弹幕间隔时间，单位秒，设置为0不发送弹幕，只支持同步
 PUSH:
  
name: "PUSH_DEER_SAMPLE" # 推送名称，对应上面对应用户的推送，请保证名称唯一
 token: "" # 推送服务TOKEN
 type: "push_deer" # 推送服务类型为 PushDeer
 url: "http:///message/push" # 推送服务URL 

name: "PUSH_PLUS_SAMPLE"
 token: ""
 type: "push_plus"
 url: "http://www.pushplus.plus/send" 

name: "TELEGRAM_SAMPLE"
 token: ""
 type: "telegram"
 url: "https://api.telegram.org/bot/sendMessage" 
 
推送服务，每日打卡成功或报错日志推送
 
目前支持PushDeer, PushPlus, Telegram

**Comment by Malus-Mill** [comment]
> 我忘记我的代码逻辑了，但是你又有黑又有白的是什么操作呀 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: PlayerNeo ***@***.***&gt; 发送时间: 2022年7月11日 00:34 收件人: ThreeCatsLoveFish/MedalHelper ***@***.***&gt; 抄送: Zhimin Sun ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [ThreeCatsLoveFish/MedalHelper] 和python版的一样、白名单也是坏的 (Issue #25) USERS: access_key: XXX # 注意冒号后的空格 否则会读取失败 英文冒号 allowed_uid: 23553760,23240551,14327465,21693691,399,958617,631,22686795 # 白名单UID,填了后将覆盖配置只打卡，点赞，分享这些用户的勋章 用英文逗号分隔 不填则不限制 banned_uid: 789,100,884239,14085407,23455498,2416317,22435949,23031701 # 黑名单UID,填了后将不会打卡，点赞，分享 用英文逗号分隔 不填则不限制 push_name: # 推送服务，留空表示不需要推送 access_key: allowed_uid: banned_uid: push_name: 注意对齐 多用户以上格式添加 井号后为注释 井号前后必须有空格 DANMU: [ ".", ] 可在此处自定义打卡弹幕 CRON: #3 2 1 * * 这里是 cron 表达式, 从左到右参数为秒，分钟，小时，日期，月份 Second | Minute | Hour | Dom | Month 例如每天凌晨01点02分03秒执行一次为 3 2 1 * * 如果不填,则不使用内置定时器,填写正确后要保持该进程一直运行 CD: async: 0 # 异步执行，默认为1表示异步，0表示同步 retry: 1 # 任务失败重试时间，单位秒，设置为0不重试 max_try: 10 # 任务失败最多重试次数，单位次，设置为0不重试 like: 5 # 点赞间隔时间，单位秒，设置为0不点赞 share: 10 # 分享间隔时间，单位秒，设置为0不分享 danmu: 5 # 弹幕间隔时间，单位秒，设置为0不发送弹幕，只支持同步 PUSH: name: "PUSH_DEER_SAMPLE" # 推送名称，对应上面对应用户的推送，请保证名称唯一 token: "" # 推送服务TOKEN type: "push_deer" # 推送服务类型为 PushDeer url: "http:///message/push" # 推送服务URL name: "PUSH_PLUS_SAMPLE" token: "" type: "push_plus" url: "http://www.pushplus.plus/send" name: "TELEGRAM_SAMPLE" token: "" type: "telegram" url: "https://api.telegram.org/bot/sendMessage" 推送服务，每日打卡成功或报错日志推送 目前支持PushDeer, PushPlus, Telegram — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

删掉黑名单还是一样啊

**Comment by ThreeCatsLoveFish** [comment]
> USERS:
>       allowed_uid: 23553760,23240551,14327465,21693691,399,958617,631,22686795 # 白名单UID,填了后将覆盖配置只打卡，点赞，分享这些用户的勋章 用英文逗号分隔 不填则不限制

你确定你这些输入的是uid不是直播间房间号是吧
