### ISSUE TITLE
[BUG] Doesn't work well on debian

### ISSUE THREAD

**Issue by qaqland** [ThreeCatsLoveFish/MedalHelper#29]
```
$ ./medal_linux login
./medal_linux: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /medal_linux)

$ ldd --version
ldd (Debian GLIBC 2.33-8) 2.33

$ uname -a
Linux debian 5.18.0-3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.14-1 (2022-07-23) x86_64 GNU/Linux
```
medal_linux is last version from github release

**Comment by ThreeCatsLoveFish** [comment]
应该是你的debian的C库版本不够，你要不试试看git clone一下源代码编译？

**Comment by qaqland** [comment]
Your glibc version is too high to build release.

**Comment by ThreeCatsLoveFish** [comment]
> Your glibc version is too high to build release.

I mean, you need to config GO 1.18 first, and then compile the source code to build and run.

If you feel that using this script is too difficult for you to use, you can use the [python version](https://github.com/XiaoMiku01/fansMedalHelper)
