### ISSUE TITLE
[Feat] Send notification when running error

### ISSUE THREAD

**Issue by gitiray** [ThreeCatsLoveFish/MedalHelper#30]
**Is your feature request related to a problem? Please describe.**
登录状态过期，当天任务未完成。事后发现断签，翻看运行日志才看到
```
[ERROR]用户登录失败, accessKey:
```

**Describe the solution you'd like**
在出现运行故障时也推送通知提醒

**Comment by ThreeCatsLoveFish** [comment]
重新扫码登陆一下
一个月一次

**Comment by gitiray** [comment]
我是改了密码，然后主动更新了key的，但是没有重启容器，导致容器内没读取刷新。
能推送提醒运行故障会更完善点，至少看到推送报错当天还能手动修正，不至于断签。

**Comment by ThreeCatsLoveFish** [comment]
> 我是改了密码，然后主动更新了key的，但是没有重启容器，导致容器内没读取刷新。 能推送提醒运行故障会更完善点，至少看到推送报错当天还能手动修正，不至于断签。

推送在家了，我另一个仓库是加了这个accesskey过期推送的，这个忘记加了
