### ISSUE TITLE
docker build时出现问题

### ISSUE THREAD

**Issue by hnnw** [ThreeCatsLoveFish/MedalHelper#4]
Sending build context to Docker daemon  204.3kB
Step 1/9 : FROM golang:1 AS builder
 ---> 738636f06010
Step 2/9 : COPY . /app
 ---> Using cache
 ---> c096a859cb64
Step 3/9 : ARG CGO_ENABLED=0
 ---> Using cache
 ---> 7cdddda92991
Step 4/9 : ARG GOPROXY=https://goproxy.cn,direct
 ---> Using cache
 ---> fabc75acd53b
Step 5/9 : RUN cd /app &&     go build -o /medalhelper /app
 ---> Using cache
 ---> a5651ae57a93
Step 6/9 : FROM gcr.io/distroless/static
Get "https://gcr.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

在Docker Desktop中build依然拉取失败
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head "https://gcr.io/v2/distroless/static/manifests/latest": Service Unavailable

已经使用阿里镜像源

**Comment by ThreeCatsLoveFish** [comment]
@JokerQyou 好兄弟帮忙看看？

**Comment by JokerQyou** [comment]
我看看 dockerhub 有无 distroless 的镜像
