### ISSUE TITLE
按照使用手册 docker run --rm -ti medalhelper login 报错

### ISSUE THREAD

**Issue by hnnw** [ThreeCatsLoveFish/MedalHelper#5]
换了国外服务器拉起了镜像，执行登录时报错
docker run --rm -ti medalhelper login
panic: open users.yaml: no such file or directory

goroutine 1 [running]:
MedalHelper/util.InitConfig()
        /app/util/config.go:49 +0x105
main.init.0()
        /app/main.go:19 +0x2e

**Comment by ThreeCatsLoveFish** [comment]
这个应该是配置文件没有加载到目录下，这个docker可能要改一下配置，或者我仓库的代码改一下

**Comment by ThreeCatsLoveFish** [comment]
你如果现在想要用的话就把容器里的users.yaml文件copy一份到/app/目录下

**Comment by ThreeCatsLoveFish** [comment]
> 换了国外服务器拉起了镜像，执行登录时报错 docker run --rm -ti medalhelper login panic: open users.yaml: no such file or directory
> 
> goroutine 1 [running]: MedalHelper/util.InitConfig() /app/util/config.go:49 +0x105 main.init.0() /app/main.go:19 +0x2e

你试一下修改完users yaml文件之后直接运行
docker run -d \
    -e TZ=Asia/Shanghai \
    --restart unless-stopped \
    --name medalhelper \
    medalhelper
