### ISSUE TITLE
[Support] 可手动指定完成条件

### ISSUE THREAD

**Issue by JokerQyou** [ThreeCatsLoveFish/MedalHelper#7]
**Is your feature request related to a problem? Please describe.**

测试发现只有少数直播间（不特定，每次运行都是随机几个）可以打满 1300 亲密度。大部分直播间是只能打到 1200。具体是哪一个任务没做满我不太清楚。

但代码逻辑是不全部打到 1300 不会停止。是否有可能卡在上一次任务，然后错过下一次 CRON 运行。

**Describe the solution you'd like**

配置可以加一个开关，打满 1200 就算满了，不用继续尝试打到 1300。

**Describe alternatives you've considered**

No alternative yet.

**Additional context**

我是观察了一下，所有直播间挂了大约三轮心跳，其他分享、弹幕和点赞任务应该都是满了。可能是这个观看时长没生效。而且非常诡异的是打满 1300 的那个直播间今天是没开播的。

**Comment by ThreeCatsLoveFish** [comment]
代码逻辑是重试三轮，如果开同步执行不并发可能是会影响到下一轮cron的

这个1200确实可以的加个config，我稍后改下

**Comment by JokerQyou** [comment]
原来是重试三轮，我以为无限重试的……看到它运行到第三次我就手动停了。如果有这个限制的话可能这个功能就不太需要了。我反而觉得白名单模式可能更实用一点，这个功能可以放一放。

**Comment by ThreeCatsLoveFish** [comment]
> 原来是重试三轮，我以为无限重试的……看到它运行到第三次我就手动停了。

https://github.com/ThreeCatsLoveFish/MedalHelper/blob/60dad49685e0d14c3c7a492cd1dba63ad959fb07/service/user.go#L199

> 白名单模式可能更实用一点，这个功能可以放一放。

白名单是指指定用户就一直打到1300吗

**Comment by JokerQyou** [comment]
不是，现在不是只能用黑名单模式吗，就是默认是对所有的牌子做任务，只忽略黑名单里的。
我看 python 版本它新加了一个白名单模式，就是只对指定的 UID 的牌子去做任务，忽略其他的牌子。如果牌子比较多，但是只想养其中一小部分的话，白名单可能更友好，不用复制粘贴那么多 UID。

**Comment by ThreeCatsLoveFish** [comment]
> 不是，现在不是只能用黑名单模式吗，就是默认是对所有的牌子做任务，只忽略黑名单里的。 我看 python 版本它新加了一个白名单模式，就是只对指定的 UID 的牌子去做任务，忽略其他的牌子。如果牌子比较多，但是只想养其中一小部分的话，白名单可能更友好，不用复制粘贴那么多 UID。

ok 我了解了，看起来白名单确实有需求，我本来以为大家只对黑名单感兴趣哈哈哈

**Comment by JokerQyou** [comment]
重新检查了一下b站，发现所有牌子都显示达到了1300。所以这可能只是b站那边的统计延迟（或者数据展示延迟）。暂时可以先不加1200的配置逻辑，再观察一段时间。
